import './globals.css'
import type { Metadata } from 'next'
import { montserrat } from '../../fonts'
import AuthProvider from '@/components/Authprovider'
export const metadata: Metadata = {
  title: 'Past Auction',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <AuthProvider>
        {children}
        </AuthProvider>
      </body>
    </html>
  )
}
