'use client'

import './globals.css'
import type { Metadata } from 'next'
import { montserrat } from './fonts'
import {QueryClient, QueryClientProvider} from '@tanstack/react-query'
export const metadata: Metadata = {
  title: 'Past Auction',
  description: 'Generated by create next app',
}

const queryClient = new QueryClient()
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <QueryClientProvider client={queryClient}>
      <body className={montserrat.className}>
        {children}
      </body>
      </QueryClientProvider>
    </html>
  )
}
